### ISSUE TITLE
Crowdin project: OBS Studio | Suggested translation strings left in non-approved statte

### ISSUE THREAD

**Issue by Ricky-Tigg** [obsproject/obs-crowdin-sync#10]
### Operating System Info

Other

### Other OS

No related to

### OBS Studio Version

27.2.4

### OBS Studio Log URL

not related

### Expected Behavior

Assignment of a user granted with **approval right** of suggested translation strings on Crowdin platform for **Finnish** locale

### Current Behavior

Hello _dodgepong_ – owner of the Crowdin project _OBS Studio_.

Mails sent by me to the owners of public projects hosted on [Crowdin](https://crowdin.com/) have invariably not been replied, which leads me to conclude that the service may not be operational as owners would most likely be willing to reply. Have you even received anything from me there?

Here is the common subject of those emails: Suggested translations for Finnish locale which are part of newly contributed translations, are invariably left in pending status, since they rely on approval. I translate but i have not been granted such right. Could it be that you were not aware of that situation? Unknown is the protocol observed by Github in regard to translation strings being in non-approved state. Do those strings are eligible to be merged to the present platform or are all efforts applied to translations been vain? That would be a worth knowing information to me.

### Steps to Reproduce

1. Visit Crowdin platform for your project
2. Inspect suggested translation strings in non-approved state

**Comment by Ricky-Tigg** [comment]
1. Please begin by presenting yourself. i am expecting the owner, not a **stranger**.
2. Don't get involve if your are not the owner or have not explicitly be granted the right to participate as official represent of that component there.

Only after that you would go to that site and participate in that discussion, with self explicit title,  which anyway already existed before your post.  And don't create a new one with the same subject.

**Comment by WizardCM** [comment]
Vainock is currently our most active person when it comes to anything translation related. Everything he has said up to this point is correct.

**Comment by Ricky-Tigg** [comment]
And then?

**Comment by WizardCM** [comment]
To answer your questions explicity:

1. While dodgepong is the owner of the project on crowdin, that does not mean he's the main person to reach out to in relation to Crowdin questions
2. I don't believe there is anyone actively reading messages sent to whatever mail system Crowdin uses at this time
3. As Vainock has stated already, translations don't need to be approved to be included in an OBS update
4. All your recent translations were done after February 15, which is when we last released a major OBS version, which is why they have not yet been included in an OBS build
5. Per 3) and 4), when we start the next Beta period, **we will be sure to include all translations in Crowdin (including those pending approval) in the next release**, as always
6. As Vainock has stated, for any further questions regarding Crowdin or translations, the fastest way to get a response is via the Discussion section on Crowdin
